### ISSUE TITLE
Any plans to add this to PackageControl

### ISSUE THREAD

**Issue by FichteFoll** [predragnikolic/InlineFold#5]
I've been using the package as a replacement for [Fold Python Docstrings](https://packagecontrol.io/packages/Fold%20Python%20Docstrings) for quite a while now (and also testing the HTML class folding configuration) and I think it's definitely usable in its current form.

What do you think of publishing it? I just stubled upon this package again as I was comparing my installed (in PC configuration) vs actual packages list (on disk).

**Comment by predragnikolic** [comment]
Sorry for the delay,
It will probably be published. 
I don't have an ETA for that.

**Comment by predragnikolic** [comment]
Done. :⁠-⁠)
