### ISSUE TITLE
Receipes

### ISSUE THREAD

**Issue by predragnikolic** [predragnikolic/InlineFold#8]
Hello :wave: 

Feel free to share your `"inline_fold.rules"` with others!
Add an image so we can see it in action.
Use reactions.

Only write recipes in comments :) - I will hide any unrelated comment

**Comment by gnat** [comment]
* Fold <script> (components / inline JS / scoped JS)
* Fold <style> (components / inline CSS / scoped CSS)
```json
"inline_fold.rules": {
  {
      "fold_selector": "text.html.basic  source.js.embedded.html",
  },
  {
      "fold_selector": "text.html.basic  source.css.embedded.html",
  }
}
```
